DATA_PATH = "data"
DEPENDENCIES_PATH = f"{DATA_PATH}/dependencies"
MODEL_GARDEN_PATH = f"{DEPENDENCIES_PATH}/model_garden"
PREFERRED_FILENAME = f'{DATA_PATH}/preferred.txt'
CONFIG_PATH = f"{DATA_PATH}/config.json"
SOUND_MAP_KEY = 0
AUDIBLE_REMINDERS_KEY = 1