DATA_PATH = "data"
DEPENDENCIES_PATH = f"{DATA_PATH}/dependencies"
MODEL_GARDEN_PATH = f"{DEPENDENCIES_PATH}/model_garden"

PREFERRED_FILENAME = f'preferred.txt'
PREFERRED_FILENAME_PATH = f"{DATA_PATH}/{PREFERRED_FILENAME}"
CONFIG_PATH = f"{DATA_PATH}/config.json"
SOUND_MAP_KEY = 0
AUDIBLE_REMINDERS_KEY = 1

LABELMAP_FILENAME = 'label_map.pbtxt'
LABELMAP_FILENAME_PATH = f"{DATA_PATH}/{LABELMAP_FILENAME}"